categoryProduct  and creatProduct and component Panigation
codeclubvn/erp-client pull request #20
Opened 2023-09-14 14:48 UTC by blanclt

2023-09-19 02:16 UTC, duy211099 approved these changes

2023-09-25 09:44 UTC, duy211099 commented on src/components/Panigation/Panigation.tsx
> +    onListItemChange: (_newList: ProductProps[]) => void
'newList

2023-09-25 09:44 UTC, duy211099 commented on src/components/Panigation/index.ts
> +export * from './Panigation'
Pagination

2023-09-25 09:55 UTC, duy211099 requested changes

2023-09-25 09:55 UTC, duy211099 commented on src/constants/index.ts
> +export * from './DataCreatOrder'
Create

2023-09-25 09:55 UTC, duy211099 commented on src/screens/Product/components/AddCategory.tsx
> +    const nameRef: RefObject<HTMLInputElement> = createRef()
ref này mình ko thấy dùng nhỉ?

2023-09-25 09:55 UTC, duy211099 commented on src/screens/Product/components/AddCategory.tsx
> +    const [value, setValue] = useState({
cái này tạo model Category nhé

2023-09-25 09:55 UTC, duy211099 commented on src/screens/Product/components/AddCategory.tsx
> +    const handleKeyPress = (e) => {
cái này hong hỉu gì lun

2023-09-25 09:55 UTC, duy211099 commented on src/screens/Product/components/AddCategory.tsx
> +    const handleFocusInput = (field) => {
tại sao phải handle focus te

2023-09-25 09:55 UTC, duy211099 commented on src/screens/Product/components/CategoryProduct.tsx
> +    const [addCategory, setAddCategory] = useState(false)
biến boolean nên prefix 'is' nha
isAddCategory

2023-09-25 12:31 UTC, blanclt commented on src/screens/Product/components/AddCategory.tsx
> +    const handleFocusInput = (field) => {
focus để mất cái message lỗi á. mà h dùng thư viện nên bỏ luôn r

2023-09-25 12:32 UTC, blanclt commented on src/screens/Product/components/AddCategory.tsx
> +    const handleKeyPress = (e) => {
Chỉ cho nhập số thôi á

2023-09-25 14:05 UTC, duy211099 commented on src/screens/Product/components/AddCategory.tsx
> +    const handleFocusInput = (field) => {
oki vậy bỏ đi nha bro

2023-09-25 14:05 UTC, duy211099 commented on src/screens/Product/components/AddCategory.tsx
> +    const handleKeyPress = (e) => {
đặt type='number' cho input là được nha

2023-09-26 03:40 UTC, closed without merging